# Generated by Django 3.0.5 on 2020-05-02 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[1-4][\\u0410-\\u044f]{2,4}-\\d{1,2}\\u0430?\\.\\d{2}$', 'Group name does not match rules.')], verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
