# Generated by Django 3.0.2 on 2020-01-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registrationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='unregistered_students', to='users.Group', verbose_name='Group'),
        ),
    ]
