# Generated by Django 3.0.5 on 2020-05-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('is_staff', models.BooleanField(verbose_name='Is staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unregistered_students', to='users.Group', verbose_name='Group')),
            ],
        ),
    ]
