# Generated by Django 3.0.7 on 2020-06-11 15:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_group_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('lesson_number', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_results', to='users.Student')),
            ],
            options={
                'unique_together': {('student', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField()),
                ('points', models.IntegerField()),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lesson_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='lessons.LessonResult')),
            ],
            options={
                'unique_together': {('lesson_result', 'task_number')},
            },
        ),
    ]
