# Generated by Django 3.0.5 on 2020-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresult',
            old_name='right',
            new_name='correct',
        ),
        migrations.AddField(
            model_name='lessonresult',
            name='n',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonresult',
            name='percent_correct',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
